name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  workflow_call:

jobs:
  Full-Release:
    uses: ./.github/workflows/automated.yml
    secrets: inherit

  release:
    needs:
      - Full-Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate and Push Version Tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION_TAG="${{ github.ref_name }}"
          else
            OFFSET=-28
            RUN_NUM=${{ github.run_number }}
            TAG_BUILD=$((OFFSET + RUN_NUM))
            VERSION_TAG="v3.3.0-${TAG_BUILD}"
            
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "$VERSION_TAG"
            git push origin "$VERSION_TAG"
          fi

          echo "TAG_NAME=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          generate_release_notes: true
          body: |
            * Synced with Upstream Changes.
            * Latest patch included
            
            ~by Justus26🎖️
          files: |
            release_assets/**/*.apk
            release_assets/**/*.zip
          draft: false
          prerelease: false
